# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-12 11:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_feed_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feeds.Categorie'),
        ),
    ]
