# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-25 11:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wish_list', '0002_auto_20170825_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='product',
        ),
    ]
