# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-24 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20170818_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='message',
            field=models.TextField(default='Welcome to my store, how can I help you?', max_length=255),
        ),
    ]
