# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-23 13:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shop.models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boutique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nom')),
                ('logo', models.ImageField(null=True, upload_to=shop.models.group_based_upload, verbose_name='Logo_Boutique')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=250)),
                ('descreption', models.CharField(max_length=250)),
                ('logo', models.ImageField(null=True, upload_to=shop.models.group_based_upload_to)),
                ('logo1', models.ImageField(blank=True, default=None, upload_to=shop.models.group_based_upload_to)),
                ('logo2', models.ImageField(blank=True, null=True, upload_to=shop.models.group_based_upload_to)),
                ('logo3', models.ImageField(blank=True, null=True, upload_to=shop.models.group_based_upload_to)),
                ('is_favorite', models.BooleanField(default=False)),
                ('categorie', models.CharField(choices=[('Tous les produits', 'Tous les produits'), ('Bijoux', 'Bijoux'), ('Maison et ameublement', 'Maison et ameublement'), ('Vetement', 'Vetement'), ('Art et collections', 'Art et collections'), ('Accessoires', 'Accessoires')], default=None, max_length=250)),
                ('typeProduit', models.CharField(choices=[('Faits à main', 'Faits à main'), ('Vintage', 'Vintage')], default=None, max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('quantite', models.IntegerField(default=None)),
                ('Genre', models.CharField(choices=[('homme et femme', 'homme et femme'), ('homme', 'homme'), ('femme', 'femme')], max_length=250, null=True)),
                ('pour', models.CharField(choices=[('standard', 'standard'), ('bebe', 'bebe'), ('enfant', 'enfant'), ('jeune', 'jeune'), ('adulte', 'adulte')], max_length=250, null=True)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Boutique')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
