# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-24 20:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boutique',
            name='visitors',
            field=models.ManyToManyField(related_name='visiteurs', to=settings.AUTH_USER_MODEL),
        ),
    ]
