# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-25 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish_list', '0003_remove_wishlist_product'),
        ('shop', '0002_boutique_visitors'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='product',
            field=models.ManyToManyField(to='wish_list.Wishlist'),
        ),
    ]
