# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-25 11:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_produit_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='product',
        ),
    ]
