# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-28 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_produit_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boutique',
            name='logo',
            field=models.ImageField(null=True, upload_to=shop.models.group_based_upload, verbose_name='Shop Logo'),
        ),
        migrations.AlterField(
            model_name='boutique',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='categorie',
            field=models.CharField(choices=[('All products', 'Tous les produits'), ('Jewelry', 'Bijoux'), ('Maison et ameublement', 'Maison et ameublement'), ('Vetement', 'Vetement'), ('Art et collections', 'Art et collections'), ('Accessoires', 'Accessoires')], default=None, max_length=250),
        ),
    ]
