# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-28 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20170828_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='categorie',
            field=models.CharField(choices=[('Tous les produits', 'Tous les produits'), ('Bijoux', 'Jewelry'), ('Maison et ameublement', 'Maison et ameublement'), ('Vetement', 'Vetement'), ('Art et collections', 'Art et collections'), ('Accessoires', 'Accessoires')], default=None, max_length=250),
        ),
    ]
