# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-28 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20170828_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='Genre',
            field=models.CharField(choices=[('Men & women', 'Men & women'), ('Men', 'Men'), ('Women', 'Women')], max_length=250, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='boutique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Boutique', verbose_name='Shop'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='categorie',
            field=models.CharField(choices=[('All products', 'All products'), ('Jewelry', 'Jewelry'), ('Home & Furnishings', 'Home & Furnishings'), ('Clothes', 'Clothes'), ('Art et collections', 'Art et collections'), ('Accessoires', 'Accessoires')], default=None, max_length=250, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='descreption',
            field=models.CharField(max_length=250, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='logo',
            field=models.ImageField(null=True, upload_to=shop.models.group_based_upload_to, verbose_name='Principal photo'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='pour',
            field=models.CharField(choices=[('standard', 'standard'), ('baby', 'baby'), ('child', 'child'), ('young', 'young'), ('adult', 'adult')], max_length=250, null=True, verbose_name='For'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix',
            field=models.IntegerField(null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='quantite',
            field=models.IntegerField(default=None, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='typeProduit',
            field=models.CharField(choices=[('Handmade', 'Handmade'), ('Vintage', 'Vintage')], default=None, max_length=250, verbose_name='Type'),
        ),
    ]
