# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-28 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20170828_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='categorie',
            field=models.CharField(choices=[('All products', 'All products'), ('Jewelry', 'Jewelry'), ('Home & Furnishings', 'Home & Furnishings'), ('Clothes', 'Clothes'), ('Art & collections', 'Art & collections'), ('Accessoires', 'Accessoires')], default=None, max_length=250, verbose_name='Category'),
        ),
    ]
