# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-13 23:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20170812_1235'),
        ('reaction', '0002_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post.Post'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='type',
            field=models.CharField(blank=True, choices=[('NORMAL', 'normal'), ('SMILE', 'smile'), ('LOVE', 'love'), ('WISH', 'wish'), ('LIKE', 'like'), ('DISLIKE', 'dislike')], max_length=255, null=True),
        ),
    ]
