# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-15 09:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20170812_1235'),
        ('shop', '0002_auto_20170809_2314'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reaction', '0004_auto_20170814_0047'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reaction',
            unique_together=set([('user', 'produit', 'post')]),
        ),
    ]
